version: '3.8'

services:
  database:
    container_name: database-GIM
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4399:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php-GIM
    build:
      context: ./php
    ports:
      - '9099:9000'
    volumes:
      - ../app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx-GIM
    image: nginx:stable-alpine
    ports:
      - '99:80'
    volumes:
      - ../app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database