controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

connect_google_start:
    path: /connect/
    controller: App\Controller\SecurityController::connect






